# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: phtruong <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/09/21 09:21:46 by phtruong          #+#    #+#              #
#    Updated: 2019/09/21 10:10:10 by phtruong         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM debian:latest

RUN apt-get update && apt-get upgrade -y \
	&& apt-get install -y \
	sudo \
	wget \
	curl \
	bzip2 \
	vim

